In [49]:
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import importlib
import wrf

from classes import (
    CoordinateField,
    ScalarField
)
from helpers import (
    great_circle_distance,
    w_to_omega
)

# f = xr.open_mfdataset('../data/*.nc')
f['lev'] = [880., 865., 850., 835., 820., 550., 525., 500., 475., 450.]
f.to_netcdf('../data/2013.11.18_regrid.nc')

In [29]:
c = CoordinateField(f.lat, f.lon, great_circle_distance)
s = ScalarField(f.U, c.dx, c.dy)

dUdx = s.get_ddx()
dUdy = s.get_ddy()

omega = w_to_omega(w=f.W, temp=f.TK, qv=f.Q, p=f.lev)

In [30]:
time_index = 1
p_index = 2
lat_index = 3
lon_index = 4

p = f.lev[p_index]
temp = f.TK[time_index, p_index, lat_index, lon_index]
w = f.W[time_index, p_index, lat_index, lon_index]
qv = f.Q[time_index, p_index, lat_index, lon_index]

g = 9.81        # m/s**2
rgas = 287.04   # J/K/kg
eps = 0.622

density = (p / (rgas*temp)) * (eps * (1 + qv) / (eps + qv))

omega_test = -g * w * density

print(omega_test, omega[time_index, p_index, lat_index, lon_index])

<xarray.DataArray ()>
array(-0.000208)
Coordinates:
    lon      float64 3.6
    lat      float64 66.15
    XTIME    datetime64[ns] 2013-11-18T07:00:00
    lev      float64 850.0 <xarray.DataArray ()>
array(-0.000208)
Coordinates:
    lon      float64 3.6
    lat      float64 66.15
    XTIME    datetime64[ns] 2013-11-18T07:00:00
    lev      float64 850.0


In [17]:
a = np.array([
    [
        [
            [1,1,1,1],
            [2,2,2,2]
        ],
        [
            [3,3,3,3],
            [4,4,4,4]
        ],
    ],
    [
        [
            [5,5,5,5],
            [6,6,6,6]
        ],
        [
            [7,7,7,7],
            [8,8,8,8]
        ],
    ],
])
b = np.array(
    [
        [
            [1,1,1,1],
            [2,2,2,2]
        ],
        [
            [3,3,3,3],
            [4,4,4,4]
        ],
    ],
)

divisor = np.array([1, 2])

divisor[:, np.newaxis, np.newaxis]

divisor[:, np.newaxis, np.newaxis]/a

array([[[[1.        , 1.        , 1.        , 1.        ],
         [0.5       , 0.5       , 0.5       , 0.5       ]],

        [[0.66666667, 0.66666667, 0.66666667, 0.66666667],
         [0.5       , 0.5       , 0.5       , 0.5       ]]],


       [[[0.2       , 0.2       , 0.2       , 0.2       ],
         [0.16666667, 0.16666667, 0.16666667, 0.16666667]],

        [[0.28571429, 0.28571429, 0.28571429, 0.28571429],
         [0.25      , 0.25      , 0.25      , 0.25      ]]]])

In [40]:
np.reshape(a, (-1), order="C")

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6, 7, 7, 7, 7, 8, 8, 8, 8])

In [63]:
a = np.array([[[1, 5, 9, 13], [2, 6, 10, 14]], [[4, 8, 12, 16], [4, 8, 12, 16]]])

In [64]:
np.gradient(a, axis=0)

array([[[3., 3., 3., 3.],
        [2., 2., 2., 2.]],

       [[3., 3., 3., 3.],
        [2., 2., 2., 2.]]])

In [78]:
def test_func(row):
    return np.sum(row)
    
np.apply_along_axis(test_func, 0, a)

array([[ 5, 13, 21, 29],
       [ 6, 14, 22, 30]])

In [81]:
np.insert(a, 0, [1, 100], axis=-1)

array([[[  1,   1,   5,   9,  13],
        [100,   2,   6,  10,  14]],

       [[  1,   4,   8,  12,  16],
        [100,   4,   8,  12,  16]]])

In [13]:
fd = np.array([(1, 2), (1, 3), (1, 4)])

In [85]:
augh = np.array([1, 2, 3])

x = np.delete(augh, 0)

In [88]:
a.shape[-2]

2

In [42]:
f.lev

<xarray.DataArray 'lev' (lev: 10)>
array([880., 865., 850., 835., 820., 550., 525., 500., 475., 450.])
Coordinates:
  * lev      (lev) float64 880.0 865.0 850.0 835.0 ... 525.0 500.0 475.0 450.0

In [22]:
np.reshape(a, (-1))

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6, 7, 7, 7, 7, 8, 8, 8, 8])

In [24]:
list((1, 2, 3)) < 1

TypeError: '<' not supported between instances of 'list' and 'int'

In [31]:
f = f.isel(lev=slice(0, 5))

In [34]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [35]:
(meh, sad) = (1, 2)

In [36]:
meh

1

In [37]:
sad

2

In [58]:
f.W[-9, 0, :, :]

<xarray.DataArray 'W' (lat: 270, lon: 370)>
array([[ 0.022839,  0.021565,  0.020461, ..., -0.023529,  0.091806,  0.192445],
       [ 0.021315,  0.022669,  0.021565, ..., -0.040189,  0.118742,  0.167727],
       [ 0.01652 ,  0.022839,  0.022668, ..., -0.043756,  0.11635 ,  0.101954],
       ...,
       [ 0.012025,  0.006731,  0.003095, ..., -0.011058, -0.006555, -0.003922],
       [ 0.011823,  0.006979,  0.002785, ..., -0.004747, -0.003649, -0.003248],
       [ 0.011215,  0.005595,  0.00062 , ..., -0.001121, -0.00106 , -0.001612]],
      dtype=float32)
Coordinates:
  * lon      (lon) float64 3.0 3.15 3.3 3.45 3.6 ... 57.75 57.9 58.05 58.2 58.35
  * lat      (lat) float64 66.0 66.05 66.1 66.15 66.2 ... 79.3 79.35 79.4 79.45
    XTIME    datetime64[ns] 2013-11-20T16:00:00
    lev      float64 880.0
Attributes:
    long_name:    Z-wind component
    units:        m s-1
    description:  z-wind component
    FieldType:    104
    stagger:       

In [72]:
f.HFX

<xarray.DataArray 'HFX' (XTIME: 67, lat: 270, lon: 370)>
dask.array<shape=(67, 270, 370), dtype=float32, chunksize=(67, 270, 370)>
Coordinates:
  * lon      (lon) float64 3.0 3.15 3.3 3.45 3.6 ... 57.75 57.9 58.05 58.2 58.35
  * lat      (lat) float64 66.0 66.05 66.1 66.15 66.2 ... 79.3 79.35 79.4 79.45
  * XTIME    (XTIME) datetime64[ns] 2013-11-18T06:00:00 ... 2013-11-21
Attributes:
    units:        W m-2
    FieldType:    104
    MemoryOrder:  XY 
    description:  UPWARD HEAT FLUX AT THE SURFACE
    stagger:      

In [80]:
f.Q

<xarray.DataArray 'Q' (XTIME: 67, lev: 10, lat: 270, lon: 370)>
dask.array<shape=(67, 10, 270, 370), dtype=float32, chunksize=(67, 10, 270, 370)>
Coordinates:
  * lon      (lon) float64 3.0 3.15 3.3 3.45 3.6 ... 57.75 57.9 58.05 58.2 58.35
  * lat      (lat) float64 66.0 66.05 66.1 66.15 66.2 ... 79.3 79.35 79.4 79.45
  * XTIME    (XTIME) datetime64[ns] 2013-11-18T06:00:00 ... 2013-11-21
  * lev      (lev) float64 880.0 865.0 850.0 835.0 ... 525.0 500.0 475.0 450.0
Attributes:
    long_name:    Water vapor mixing ratio
    units:        kg kg-1
    description:  Water vapor mixing ratio
    FieldType:    104

In [79]:
f.isel(lev=slice(1, 4), lat=slice(100, 110), lon=slice(100, 110)).U[1, 1].values

array([[ -7.8489203,  -8.190207 ,  -8.515858 ,  -8.608485 ,  -8.625856 ,
         -8.771417 ,  -8.783806 ,  -8.816088 ,  -8.744299 ,  -8.642086 ],
       [ -8.48658  ,  -8.779866 ,  -9.087187 ,  -9.158262 ,  -9.160623 ,
         -9.266253 ,  -9.253261 ,  -9.179844 ,  -9.178572 ,  -9.101691 ],
       [ -9.045821 ,  -9.36234  ,  -9.641285 ,  -9.690358 ,  -9.66053  ,
         -9.793297 ,  -9.731135 ,  -9.64497  ,  -9.635209 ,  -9.518249 ],
       [ -9.648887 ,  -9.921314 , -10.039349 , -10.201505 , -10.222692 ,
        -10.279758 , -10.207149 , -10.090092 , -10.050836 ,  -9.960148 ],
       [-10.226849 , -10.498546 , -10.586646 , -10.735505 , -10.760147 ,
        -10.687649 , -10.677529 , -10.585637 , -10.515052 , -10.355599 ],
       [-10.815898 , -11.055432 , -11.11137  , -11.274778 , -11.2366905,
        -11.162092 , -11.111352 , -10.976476 , -10.877798 , -10.713261 ],
       [-11.279867 , -11.565483 , -11.665872 , -11.729757 , -11.689391 ,
        -11.5884495, -11.513205 , -11.385466 

In [ ]:
from classes import (ScalarField, CoordinateField)

tf = f.isel(lev=slice(1, 4), lat=slice(100, 110), lon=slice(100, 110))

