In [1]:
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import importlib
import wrf
import pandas as pd

from classes import (
    CoordinateField,
    ScalarField
)
from helpers import (
    great_circle_distance,
    w_to_omega
)

# f = xr.open_mfdataset('../data/*.nc')
# f['lev'] = np.array([880.0, 865.0, 850., 835., 820., 550., 525., 500., 475., 450.])
# f.to_netcdf('../data/2013.11.18_regrid.nc')

f = xr.open_dataset('../data/2013.11.18_regrid.nc')
low_file = pd.read_csv("../data/PL_2013-11-18-0600_20-4km_stormtrack1.csv")

dump = xr.open_dataset('../data/2013.11.18_calc_data_dump.nc')

In [29]:
c = CoordinateField(f.lat, f.lon, great_circle_distance)
s = ScalarField(f.U, c.dx, c.dy)

dUdx = s.get_ddx()
dUdy = s.get_ddy()

omega = w_to_omega(w=f.W, temp=f.TK, qv=f.Q, p=f.lev)

In [30]:
time_index = 1
p_index = 2
lat_index = 3
lon_index = 4

p = f.lev[p_index]
temp = f.TK[time_index, p_index, lat_index, lon_index]
w = f.W[time_index, p_index, lat_index, lon_index]
qv = f.Q[time_index, p_index, lat_index, lon_index]

g = 9.81        # m/s**2
rgas = 287.04   # J/K/kg
eps = 0.622

density = (p / (rgas*temp)) * (eps * (1 + qv) / (eps + qv))

omega_test = -g * w * density

print(omega_test, omega[time_index, p_index, lat_index, lon_index])

<xarray.DataArray ()>
array(-0.000208)
Coordinates:
    lon      float64 3.6
    lat      float64 66.15
    XTIME    datetime64[ns] 2013-11-18T07:00:00
    lev      float64 850.0 <xarray.DataArray ()>
array(-0.000208)
Coordinates:
    lon      float64 3.6
    lat      float64 66.15
    XTIME    datetime64[ns] 2013-11-18T07:00:00
    lev      float64 850.0


In [17]:
a = np.array([
    [
        [
            [1,1,1,1],
            [2,2,2,2]
        ],
        [
            [3,3,3,3],
            [4,4,4,4]
        ],
    ],
    [
        [
            [5,5,5,5],
            [6,6,6,6]
        ],
        [
            [7,7,7,7],
            [8,8,8,8]
        ],
    ],
])
b = np.array(
    [
        [
            [1,1,1,1],
            [2,2,2,2]
        ],
        [
            [3,3,3,3],
            [4,4,4,4]
        ],
    ],
)

divisor = np.array([1, 2])

divisor[:, np.newaxis, np.newaxis]

divisor[:, np.newaxis, np.newaxis]/a

array([[[[1.        , 1.        , 1.        , 1.        ],
         [0.5       , 0.5       , 0.5       , 0.5       ]],

        [[0.66666667, 0.66666667, 0.66666667, 0.66666667],
         [0.5       , 0.5       , 0.5       , 0.5       ]]],


       [[[0.2       , 0.2       , 0.2       , 0.2       ],
         [0.16666667, 0.16666667, 0.16666667, 0.16666667]],

        [[0.28571429, 0.28571429, 0.28571429, 0.28571429],
         [0.25      , 0.25      , 0.25      , 0.25      ]]]])

In [40]:
np.reshape(a, (-1), order="C")

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6, 7, 7, 7, 7, 8, 8, 8, 8])

In [63]:
a = np.array([[[1, 5, 9, 13], [2, 6, 10, 14]], [[4, 8, 12, 16], [4, 8, 12, 16]]])

In [64]:
np.gradient(a, axis=0)

array([[[3., 3., 3., 3.],
        [2., 2., 2., 2.]],

       [[3., 3., 3., 3.],
        [2., 2., 2., 2.]]])

In [78]:
def test_func(row):
    return np.sum(row)
    
np.apply_along_axis(test_func, 0, a)

array([[ 5, 13, 21, 29],
       [ 6, 14, 22, 30]])

In [81]:
np.insert(a, 0, [1, 100], axis=-1)

array([[[  1,   1,   5,   9,  13],
        [100,   2,   6,  10,  14]],

       [[  1,   4,   8,  12,  16],
        [100,   4,   8,  12,  16]]])

In [13]:
fd = np.array([(1, 2), (1, 3), (1, 4)])

In [85]:
augh = np.array([1, 2, 3])

x = np.delete(augh, 0)

In [88]:
a.shape[-2]

2

In [42]:
f.lev

<xarray.DataArray 'lev' (lev: 10)>
array([880., 865., 850., 835., 820., 550., 525., 500., 475., 450.])
Coordinates:
  * lev      (lev) float64 880.0 865.0 850.0 835.0 ... 525.0 500.0 475.0 450.0

In [22]:
np.reshape(a, (-1))

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6, 7, 7, 7, 7, 8, 8, 8, 8])

In [24]:
list((1, 2, 3)) < 1

TypeError: '<' not supported between instances of 'list' and 'int'

In [31]:
f = f.isel(lev=slice(0, 5))

In [34]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [35]:
(meh, sad) = (1, 2)

In [36]:
meh

1

In [37]:
sad

2

In [58]:
f.W[-9, 0, :, :]

<xarray.DataArray 'W' (lat: 270, lon: 370)>
array([[ 0.022839,  0.021565,  0.020461, ..., -0.023529,  0.091806,  0.192445],
       [ 0.021315,  0.022669,  0.021565, ..., -0.040189,  0.118742,  0.167727],
       [ 0.01652 ,  0.022839,  0.022668, ..., -0.043756,  0.11635 ,  0.101954],
       ...,
       [ 0.012025,  0.006731,  0.003095, ..., -0.011058, -0.006555, -0.003922],
       [ 0.011823,  0.006979,  0.002785, ..., -0.004747, -0.003649, -0.003248],
       [ 0.011215,  0.005595,  0.00062 , ..., -0.001121, -0.00106 , -0.001612]],
      dtype=float32)
Coordinates:
  * lon      (lon) float64 3.0 3.15 3.3 3.45 3.6 ... 57.75 57.9 58.05 58.2 58.35
  * lat      (lat) float64 66.0 66.05 66.1 66.15 66.2 ... 79.3 79.35 79.4 79.45
    XTIME    datetime64[ns] 2013-11-20T16:00:00
    lev      float64 880.0
Attributes:
    long_name:    Z-wind component
    units:        m s-1
    description:  z-wind component
    FieldType:    104
    stagger:       

In [72]:
f.HFX

<xarray.DataArray 'HFX' (XTIME: 67, lat: 270, lon: 370)>
dask.array<shape=(67, 270, 370), dtype=float32, chunksize=(67, 270, 370)>
Coordinates:
  * lon      (lon) float64 3.0 3.15 3.3 3.45 3.6 ... 57.75 57.9 58.05 58.2 58.35
  * lat      (lat) float64 66.0 66.05 66.1 66.15 66.2 ... 79.3 79.35 79.4 79.45
  * XTIME    (XTIME) datetime64[ns] 2013-11-18T06:00:00 ... 2013-11-21
Attributes:
    units:        W m-2
    FieldType:    104
    MemoryOrder:  XY 
    description:  UPWARD HEAT FLUX AT THE SURFACE
    stagger:      

In [80]:
f.Q

<xarray.DataArray 'Q' (XTIME: 67, lev: 10, lat: 270, lon: 370)>
dask.array<shape=(67, 10, 270, 370), dtype=float32, chunksize=(67, 10, 270, 370)>
Coordinates:
  * lon      (lon) float64 3.0 3.15 3.3 3.45 3.6 ... 57.75 57.9 58.05 58.2 58.35
  * lat      (lat) float64 66.0 66.05 66.1 66.15 66.2 ... 79.3 79.35 79.4 79.45
  * XTIME    (XTIME) datetime64[ns] 2013-11-18T06:00:00 ... 2013-11-21
  * lev      (lev) float64 880.0 865.0 850.0 835.0 ... 525.0 500.0 475.0 450.0
Attributes:
    long_name:    Water vapor mixing ratio
    units:        kg kg-1
    description:  Water vapor mixing ratio
    FieldType:    104

In [79]:
f.isel(lev=slice(1, 4), lat=slice(100, 110), lon=slice(100, 110)).U[1, 1].values

array([[ -7.8489203,  -8.190207 ,  -8.515858 ,  -8.608485 ,  -8.625856 ,
         -8.771417 ,  -8.783806 ,  -8.816088 ,  -8.744299 ,  -8.642086 ],
       [ -8.48658  ,  -8.779866 ,  -9.087187 ,  -9.158262 ,  -9.160623 ,
         -9.266253 ,  -9.253261 ,  -9.179844 ,  -9.178572 ,  -9.101691 ],
       [ -9.045821 ,  -9.36234  ,  -9.641285 ,  -9.690358 ,  -9.66053  ,
         -9.793297 ,  -9.731135 ,  -9.64497  ,  -9.635209 ,  -9.518249 ],
       [ -9.648887 ,  -9.921314 , -10.039349 , -10.201505 , -10.222692 ,
        -10.279758 , -10.207149 , -10.090092 , -10.050836 ,  -9.960148 ],
       [-10.226849 , -10.498546 , -10.586646 , -10.735505 , -10.760147 ,
        -10.687649 , -10.677529 , -10.585637 , -10.515052 , -10.355599 ],
       [-10.815898 , -11.055432 , -11.11137  , -11.274778 , -11.2366905,
        -11.162092 , -11.111352 , -10.976476 , -10.877798 , -10.713261 ],
       [-11.279867 , -11.565483 , -11.665872 , -11.729757 , -11.689391 ,
        -11.5884495, -11.513205 , -11.385466 

In [5]:
f.sel(lev=[880, 850])

<xarray.Dataset>
Dimensions:  (XTIME: 67, lat: 270, lev: 2, lon: 370)
Coordinates:
  * lon      (lon) float64 3.0 3.15 3.3 3.45 3.6 ... 57.75 57.9 58.05 58.2 58.35
  * lat      (lat) float64 66.0 66.05 66.1 66.15 66.2 ... 79.3 79.35 79.4 79.45
  * XTIME    (XTIME) datetime64[ns] 2013-11-18T06:00:00 ... 2013-11-21
  * lev      (lev) float64 880.0 850.0
Data variables:
    HFX      (XTIME, lat, lon) float32 ...
    LH       (XTIME, lat, lon) float32 ...
    Q        (XTIME, lev, lat, lon) float32 ...
    Q2       (XTIME, lat, lon) float32 ...
    T2       (XTIME, lat, lon) float32 ...
    TK       (XTIME, lev, lat, lon) float32 ...
    U        (XTIME, lev, lat, lon) float32 ...
    U10      (XTIME, lat, lon) float32 ...
    V        (XTIME, lev, lat, lon) float32 ...
    V10      (XTIME, lat, lon) float32 ...
    W        (XTIME, lev, lat, lon) float32 ...
    Z        (XTIME, lev, lat, lon) float32 ...
Attributes:
    CDI:          Climate Data Interface version 1.7.2 (http://mpimet.mp

In [34]:
np.mean([1,2,3])

2.0

In [43]:
f.lon.sel(lon=[3.1,3.3,3.1], method="nearest")

<xarray.DataArray 'lon' (lon: 3)>
array([3.15, 3.3 , 3.15])
Coordinates:
  * lon      (lon) float64 3.15 3.3 3.15
Attributes:
    standard_name:  longitude
    long_name:      longitude
    units:          degrees_east
    axis:           X

In [52]:
f.lon.sel(lon=x["Longitude"].values, method="nearest")

<xarray.DataArray 'lon' (lon: 67)>
array([58.35,  7.8 ,  9.75, 10.8 , 12.15, 12.75, 13.95, 14.55, 16.2 , 16.8 ,
       17.85, 18.45, 19.5 , 19.65, 20.1 , 22.5 , 22.5 , 22.8 , 23.1 , 23.25,
       23.55, 23.1 , 20.1 , 19.5 , 19.65, 20.1 , 19.35, 19.5 , 21.9 , 22.05,
       21.9 , 22.8 , 23.85, 24.15, 23.7 , 23.7 , 23.85, 24.3 , 24.9 , 25.35,
       26.25, 25.95, 26.7 , 27.3 , 27.9 , 28.65, 29.4 , 30.3 , 31.95, 32.85,
       33.3 , 34.65, 35.85, 37.2 , 38.4 , 39.15, 40.35, 41.7 , 43.05, 44.7 ,
       46.2 , 47.55, 49.05, 50.7 , 58.35, 58.35, 58.35])
Coordinates:
  * lon      (lon) float64 58.35 7.8 9.75 10.8 12.15 ... 50.7 58.35 58.35 58.35
Attributes:
    standard_name:  longitude
    long_name:      longitude
    units:          degrees_east
    axis:           X

In [64]:
np.where(f.lon==7.8)[0][0]

32

In [8]:
low_file

Time step       SLP  Longitude  Latitude
0           0       NaN        NaN       NaN
1           1  979.7018   7.746967  68.74998
2           2  979.1722   9.770306  69.23523
3           3  978.1597  10.741020  69.44461
4           4  977.5530  12.115330  69.71329
5           5  976.9393  12.757710  69.89651
6           6  976.5701  13.892750  70.16076
7           7  975.9055  14.611490  70.25810
8           8  974.8201  16.252110  70.97623
9           9  973.6800  16.730470  71.13137
10         10  972.9229  17.775330  71.40806
11         11  971.6179  18.405070  71.62937
12         12  970.8812  19.433590  71.79644
13         13  970.7113  19.658720  72.22665
14         14  970.4879  20.049440  72.51493
15         15  970.0524  22.474290  72.56805
16         16  969.5963  22.538620  72.82877
17         17  969.0505  22.787660  72.99477
18         18  968.2394  23.102240  73.12872
19         19  968.2701  23.250730  73.27666
20         20  968.4371  23.513840  73.44189
21         21  968.6301  23.144730  73.63319
22         22  968.6091  20.150290  73.77312
23         23  967.7245  19.531570  73.70712
24         24  966.9012  19.659210  73.51476
25         25  966.0200  20.150290  73.77312
26         26  965.7299  19.383130  73.63741
27         27  966.2544  19.434320  73.34483
28         28  966.2478  21.916930  73.43651
29         29  966.9396  22.090930  73.42323
..        ...       ...        ...       ...
37         37  967.3057  24.347530  72.91225
38         38  967.7201  24.897070  72.99568
39         39  967.6743  25.286800  72.85033
40         40  968.0812  26.276150  72.83236
41         41  968.3755  25.886720  72.65526
42         42  968.8702  26.633170  72.44130
43         43  969.2115  27.320460  72.33847
44         44  969.7186  27.842710  72.25143
45         45  970.3605  28.655630  72.04466
46         46  971.0621  29.404990  71.86797
47         47  971.7178  30.332930  71.82928
48         48  972.0720  31.978940  71.48486
49         49  972.7681  32.917820  71.39928
50         50  973.5834  33.348440  71.33177
51         51  974.4467  34.621190  71.12318
52         52  975.4683  35.789870  70.86112
53         53  976.7592  37.129110  70.75893
54         54  977.6171  38.427730  70.68159
55         55  978.3489  39.111090  70.18028
56         56  979.1188  40.383410  70.05328
57         57  980.1269  41.657520  69.88142
58         58  981.0950  43.043620  69.63473
59         59  982.0600  44.633000  69.56897
60         60  982.4443  46.150580  69.34138
61         61  983.4230  47.517430  69.16888
62         62  984.5175  49.055100  69.02473
63         63  985.1943  50.665140  68.93864
64         64       NaN        NaN       NaN
65         65       NaN        NaN       NaN
66         66       NaN        NaN       NaN

[67 rows x 4 columns]

In [19]:
low_data = {
    "lat": low_file["Latitude"].values,
    "lon": low_file["Longitude"].values,
    "slp": low_file["SLP"].values,
}

print("Time,Sensible Heat Flux,Latent Heat Flux")

for time_idx in range(f.XTIME.size):
    low_lat = low_data["lat"][time_idx]
    low_lon = low_data["lon"][time_idx]
    low_slp = low_data["slp"][time_idx]
    
    if np.isnan(low_lat) or np.isnan(low_lon) or np.isnan(low_slp):
        continue
        
    closest_lat = f.lat.sel(lat=low_lat, method="nearest")
    closest_lon = f.lon.sel(lon=low_lon, method="nearest")

    closest_lat_idx = np.where(f.lat==closest_lat)[0][0]
    closest_lon_idx = np.where(f.lon==closest_lon)[0][0]
    
    calc_slice = (
        time_idx,
        closest_lat_idx,
        closest_lon_idx,
    )
    
    print(str(f.XTIME[time_idx].values), f.HFX[calc_slice].values, f.LH[calc_slice].values)

Time,Sensible Heat Flux,Latent Heat Flux
2013-11-18T07:00:00.000000000 27.984997 32.843002
2013-11-18T08:00:00.000000000 30.280626 39.370197
2013-11-18T09:00:00.000000000 32.330585 49.88444
2013-11-18T10:00:00.000000000 36.865036 67.12399
2013-11-18T11:00:00.000000000 27.828548 30.219843
2013-11-18T12:00:00.000000000 45.83648 90.602745
2013-11-18T13:00:00.000000000 57.739704 67.898094
2013-11-18T14:00:00.000000000 39.101864 38.43275
2013-11-18T15:00:00.000000000 50.95084 67.445816
2013-11-18T16:00:00.000000000 69.85007 90.400734
2013-11-18T17:00:00.000000000 59.481853 65.818375
2013-11-18T18:00:00.000000000 29.399532 50.39252
2013-11-18T19:00:00.000000000 14.041142 21.888586
2013-11-18T20:00:00.000000000 16.882145 27.588352
2013-11-18T21:00:00.000000000 27.615658 32.281773
2013-11-18T22:00:00.000000000 26.514097 25.69847
2013-11-18T23:00:00.000000000 26.914015 26.821278
2013-11-19T00:00:00.000000000 23.967522 26.519651
2013-11-19T01:00:00.000000000 20.498793 22.946043
2013-11-19T02:00:

In [5]:
f

<xarray.Dataset>
Dimensions:  (XTIME: 67, lat: 270, lev: 10, lon: 370)
Coordinates:
  * lon      (lon) float64 3.0 3.15 3.3 3.45 3.6 ... 57.75 57.9 58.05 58.2 58.35
  * lat      (lat) float64 66.0 66.05 66.1 66.15 66.2 ... 79.3 79.35 79.4 79.45
  * XTIME    (XTIME) datetime64[ns] 2013-11-18T06:00:00 ... 2013-11-21
  * lev      (lev) float64 880.0 865.0 850.0 835.0 ... 525.0 500.0 475.0 450.0
Data variables:
    HFX      (XTIME, lat, lon) float32 ...
    LH       (XTIME, lat, lon) float32 ...
    Q        (XTIME, lev, lat, lon) float32 ...
    Q2       (XTIME, lat, lon) float32 ...
    T2       (XTIME, lat, lon) float32 ...
    TK       (XTIME, lev, lat, lon) float32 ...
    U        (XTIME, lev, lat, lon) float32 ...
    U10      (XTIME, lat, lon) float32 ...
    V        (XTIME, lev, lat, lon) float32 ...
    V10      (XTIME, lat, lon) float32 ...
    W        (XTIME, lev, lat, lon) float32 ...
    Z        (XTIME, lev, lat, lon) float32 ...
Attributes:
    CDI:          Climate Data 

In [7]:
f['lev'] = np.array([880.0, 865.0, 850., 835., 820., 550., 525., 500., 475., 450.])

In [11]:
f

<xarray.Dataset>
Dimensions:  (XTIME: 67, lat: 270, lev: 10, lon: 370)
Coordinates:
  * lon      (lon) float64 3.0 3.15 3.3 3.45 3.6 ... 57.75 57.9 58.05 58.2 58.35
  * lat      (lat) float64 66.0 66.05 66.1 66.15 66.2 ... 79.3 79.35 79.4 79.45
  * XTIME    (XTIME) datetime64[ns] 2013-11-18T06:00:00 ... 2013-11-21
  * lev      (lev) float64 880.0 865.0 850.0 835.0 ... 525.0 500.0 475.0 450.0
Data variables:
    HFX      (XTIME, lat, lon) float32 ...
    LH       (XTIME, lat, lon) float32 ...
    PSFC     (XTIME, lat, lon) float32 ...
    Q        (XTIME, lev, lat, lon) float32 ...
    Q2       (XTIME, lat, lon) float32 ...
    T2       (XTIME, lat, lon) float32 ...
    Qcl      (XTIME, lev, lat, lon) float32 ...
    TK       (XTIME, lev, lat, lon) float32 ...
    U        (XTIME, lev, lat, lon) float32 ...
    U10      (XTIME, lat, lon) float32 ...
    UST      (XTIME, lat, lon) float32 ...
    V        (XTIME, lev, lat, lon) float32 ...
    V10      (XTIME, lat, lon) float32 ...
    W

In [55]:
outfile = xr.Dataset()

In [31]:
np.shape(f.U)

z = np.zeros(np.shape(f.U))

In [52]:
arr = xr.DataArray(z, dims=["XTIME", "lev", "lat", "lon"])

In [60]:
outfile['AHHH'] = arr
outfile['XTIME'] = f.XTIME
outfile['lev'] = f.lev
outfile['lat'] = f.lat
outfile['lon'] = f.lon

In [61]:
outfile

<xarray.Dataset>
Dimensions:  (XTIME: 67, lat: 270, lev: 10, lon: 370)
Coordinates:
  * lon      (lon) float64 3.0 3.15 3.3 3.45 3.6 ... 57.75 57.9 58.05 58.2 58.35
  * lat      (lat) float64 66.0 66.05 66.1 66.15 66.2 ... 79.3 79.35 79.4 79.45
  * lev      (lev) float64 880.0 865.0 850.0 835.0 ... 525.0 500.0 475.0 450.0
  * XTIME    (XTIME) datetime64[ns] 2013-11-18T06:00:00 ... 2013-11-21
Data variables:
    AHHH     (XTIME, lev, lat, lon) float64 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0

In [70]:
outfile.AHHH.attrs={'help': 'text'}

In [71]:
outfile.AHHH

<xarray.DataArray 'AHHH' (XTIME: 67, lev: 10, lat: 270, lon: 370)>
array([[[[0., ..., 0.],
         ...,
         [0., ..., 0.]],

        ...,

        [[0., ..., 0.],
         ...,
         [0., ..., 0.]]],


       ...,


       [[[0., ..., 0.],
         ...,
         [0., ..., 0.]],

        ...,

        [[0., ..., 0.],
         ...,
         [0., ..., 0.]]]])
Coordinates:
  * lon      (lon) float64 3.0 3.15 3.3 3.45 3.6 ... 57.75 57.9 58.05 58.2 58.35
  * lat      (lat) float64 66.0 66.05 66.1 66.15 66.2 ... 79.3 79.35 79.4 79.45
  * lev      (lev) float64 880.0 865.0 850.0 835.0 ... 525.0 500.0 475.0 450.0
  * XTIME    (XTIME) datetime64[ns] 2013-11-18T06:00:00 ... 2013-11-21
Attributes:
    help:     text

In [2]:
dump

<xarray.Dataset>
Dimensions:                      (XTIME: 67, lat: 270, lev: 3, lon: 370)
Coordinates:
  * XTIME                        (XTIME) datetime64[ns] 2013-11-18T06:00:00 ... 2013-11-21
  * lat                          (lat) float64 66.0 66.05 66.1 ... 79.4 79.45
  * lon                          (lon) float64 3.0 3.15 3.3 ... 58.05 58.2 58.35
  * lev                          (lev) float64 880.0 850.0 820.0
Data variables:
    Q1                           (XTIME, lev, lat, lon) float64 ...
    Q2                           (XTIME, lev, lat, lon) float64 ...
    DIVQ                         (XTIME, lev, lat, lon) float64 ...
    LATENT_PHASE_CHANGE          (XTIME, lev, lat, lon) float64 ...
    DELSQ_LATENT_PHASE_CHANGE    (XTIME, lev, lat, lon) float64 ...
    W_FRIC                       (XTIME, lat, lon) float32 ...
    OMG_FRIC                     (XTIME, lat, lon) float32 ...
    OMG_TOP                      (XTIME, lat, lon) float64 ...
    HEAT_FROM_LATENT_FLUX        (XTI