In [1]:
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt

from classes import CoordinateField
from helpers import get_equidistant_lat_lon

f = xr.open_dataset('../data/2013.11.18_regrid.nc')

In [56]:
arr = np.array([[1, 2, 3], [3, 4, 3]])

np.array(zip(tuple(range(arr.ndim)), [1] * arr.ndim))

array(<zip object at 0x11f4de5c8>, dtype=object)

In [2]:
c = CoordinateField(f.lat, f.lon)

In [14]:
x = 43
y = 53

lat, lon = c.coors[y, x]

data_lat = f.U[0, 0, y, x].lat
data_lon = f.U[0, 0, y, x].lon

print(data_lon, lon)

if lat != data_lat or lon != data_lon:
    print(lat, lon)

<xarray.DataArray 'lon' ()>
array(9.45)
Coordinates:
    lon      float64 9.45
    lat      float64 68.65
    XTIME    datetime64[ns] 2013-11-18T06:00:00
    lev      float64 880.0
Attributes:
    standard_name:  longitude
    long_name:      longitude
    units:          degrees_east
    axis:           X 9.45


In [63]:
a = np.array([[[1, 5, 9, 13], [2, 6, 10, 14]], [[4, 8, 12, 16], [4, 8, 12, 16]]])

In [64]:
np.gradient(a, axis=0)

array([[[3., 3., 3., 3.],
        [2., 2., 2., 2.]],

       [[3., 3., 3., 3.],
        [2., 2., 2., 2.]]])

In [78]:
def test_func(row):
    return np.sum(row)
    
np.apply_along_axis(test_func, 0, a)

array([[ 5, 13, 21, 29],
       [ 6, 14, 22, 30]])

In [81]:
np.insert(a, 0, [1, 100], axis=-1)

array([[[  1,   1,   5,   9,  13],
        [100,   2,   6,  10,  14]],

       [[  1,   4,   8,  12,  16],
        [100,   4,   8,  12,  16]]])

In [46]:
np.array([(1, 2), (1, 3), (1, 4)])

array([[1, 2],
       [1, 3],
       [1, 4]])

In [85]:
augh = np.array([1, 2, 3])

x = np.delete(augh, 0)

In [86]:
x

array([2, 3])