In [1]:
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import importlib
import wrf

from classes import (
    CoordinateField,
    ScalarField
)
from helpers import (
    great_circle_distance,
    w_to_omega
)

f = xr.open_dataset('../data/2013.11.18_regrid.nc')

In [29]:
c = CoordinateField(f.lat, f.lon, great_circle_distance)
s = ScalarField(f.U, c.dx, c.dy)

dUdx = s.get_ddx()
dUdy = s.get_ddy()

omega = w_to_omega(w=f.W, temp=f.TK, qv=f.Q, p=f.lev)

In [30]:
time_index = 1
p_index = 2
lat_index = 3
lon_index = 4

p = f.lev[p_index]
temp = f.TK[time_index, p_index, lat_index, lon_index]
w = f.W[time_index, p_index, lat_index, lon_index]
qv = f.Q[time_index, p_index, lat_index, lon_index]

g = 9.81        # m/s**2
rgas = 287.04   # J/K/kg
eps = 0.622

density = (p / (rgas*temp)) * (eps * (1 + qv) / (eps + qv))

omega_test = -g * w * density

print(omega_test, omega[time_index, p_index, lat_index, lon_index])

<xarray.DataArray ()>
array(-0.000208)
Coordinates:
    lon      float64 3.6
    lat      float64 66.15
    XTIME    datetime64[ns] 2013-11-18T07:00:00
    lev      float64 850.0 <xarray.DataArray ()>
array(-0.000208)
Coordinates:
    lon      float64 3.6
    lat      float64 66.15
    XTIME    datetime64[ns] 2013-11-18T07:00:00
    lev      float64 850.0


In [17]:
a = np.array([
    [
        [
            [1,1,1,1],
            [2,2,2,2]
        ],
        [
            [3,3,3,3],
            [4,4,4,4]
        ],
    ],
    [
        [
            [5,5,5,5],
            [6,6,6,6]
        ],
        [
            [7,7,7,7],
            [8,8,8,8]
        ],
    ],
])
b = np.array(
    [
        [
            [1,1,1,1],
            [2,2,2,2]
        ],
        [
            [3,3,3,3],
            [4,4,4,4]
        ],
    ],
)

divisor = np.array([1, 2])

divisor[:, np.newaxis, np.newaxis]

divisor[:, np.newaxis, np.newaxis]/a

array([[[[1.        , 1.        , 1.        , 1.        ],
         [0.5       , 0.5       , 0.5       , 0.5       ]],

        [[0.66666667, 0.66666667, 0.66666667, 0.66666667],
         [0.5       , 0.5       , 0.5       , 0.5       ]]],


       [[[0.2       , 0.2       , 0.2       , 0.2       ],
         [0.16666667, 0.16666667, 0.16666667, 0.16666667]],

        [[0.28571429, 0.28571429, 0.28571429, 0.28571429],
         [0.25      , 0.25      , 0.25      , 0.25      ]]]])

In [40]:
np.reshape(a, (-1), order="C")

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6, 7, 7, 7, 7, 8, 8, 8, 8])

In [63]:
a = np.array([[[1, 5, 9, 13], [2, 6, 10, 14]], [[4, 8, 12, 16], [4, 8, 12, 16]]])

In [64]:
np.gradient(a, axis=0)

array([[[3., 3., 3., 3.],
        [2., 2., 2., 2.]],

       [[3., 3., 3., 3.],
        [2., 2., 2., 2.]]])

In [78]:
def test_func(row):
    return np.sum(row)
    
np.apply_along_axis(test_func, 0, a)

array([[ 5, 13, 21, 29],
       [ 6, 14, 22, 30]])

In [81]:
np.insert(a, 0, [1, 100], axis=-1)

array([[[  1,   1,   5,   9,  13],
        [100,   2,   6,  10,  14]],

       [[  1,   4,   8,  12,  16],
        [100,   4,   8,  12,  16]]])

In [13]:
fd = np.array([(1, 2), (1, 3), (1, 4)])

In [85]:
augh = np.array([1, 2, 3])

x = np.delete(augh, 0)

In [88]:
a.shape[-2]

2

In [42]:
f.lev

<xarray.DataArray 'lev' (lev: 10)>
array([880., 865., 850., 835., 820., 550., 525., 500., 475., 450.])
Coordinates:
  * lev      (lev) float64 880.0 865.0 850.0 835.0 ... 525.0 500.0 475.0 450.0

In [22]:
np.reshape(a, (-1))

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6, 7, 7, 7, 7, 8, 8, 8, 8])

In [24]:
list((1, 2, 3)) < 1

TypeError: '<' not supported between instances of 'list' and 'int'

In [31]:
f = f.isel(lev=slice(0, 5))

In [34]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [35]:
(meh, sad) = (1, 2)

In [36]:
meh

1

In [37]:
sad

2