In [1]:
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt

from classes import CoordinateField
from helpers import great_circle_distance

f = xr.open_dataset('../data/2013.11.18_regrid.nc')

array(<zip object at 0x11f4de5c8>, dtype=object)

In [2]:
c = CoordinateField(f.lat, f.lon, great_circle_distance)

In [4]:
c.dx

array([6.77979673, 6.76650549, 6.75320911, 6.73990758, 6.72660092,
       6.71328914, 6.69997224, 6.68665024, 6.67332315, 6.65999098,
       6.64665373, 6.63331143, 6.61996407, 6.60661167, 6.59325424,
       6.57989179, 6.56652433, 6.55315186, 6.53977441, 6.52639198,
       6.51300457, 6.49961221, 6.4862149 , 6.47281264, 6.45940546,
       6.44599336, 6.43257635, 6.41915444, 6.40572764, 6.39229597,
       6.37885942, 6.36541802, 6.35197177, 6.33852069, 6.32506477,
       6.31160404, 6.2981385 , 6.28466817, 6.27119305, 6.25771316,
       6.2442285 , 6.23073908, 6.21724492, 6.20374603, 6.19024241,
       6.17673407, 6.16322103, 6.1497033 , 6.13618089, 6.1226538 ,
       6.10912205, 6.09558565, 6.0820446 , 6.06849893, 6.05494863,
       6.04139372, 6.02783421, 6.01427011, 6.00070143, 5.98712818,
       5.97355037, 5.95996801, 5.94638112, 5.93278969, 5.91919375,
       5.9055933 , 5.89198835, 5.87837891, 5.864765  , 5.85114662,
       5.83752378, 5.8238965 , 5.81026479, 5.79662865, 5.78298

In [63]:
a = np.array([[[1, 5, 9, 13], [2, 6, 10, 14]], [[4, 8, 12, 16], [4, 8, 12, 16]]])

In [64]:
np.gradient(a, axis=0)

array([[[3., 3., 3., 3.],
        [2., 2., 2., 2.]],

       [[3., 3., 3., 3.],
        [2., 2., 2., 2.]]])

In [78]:
def test_func(row):
    return np.sum(row)
    
np.apply_along_axis(test_func, 0, a)

array([[ 5, 13, 21, 29],
       [ 6, 14, 22, 30]])

In [81]:
np.insert(a, 0, [1, 100], axis=-1)

array([[[  1,   1,   5,   9,  13],
        [100,   2,   6,  10,  14]],

       [[  1,   4,   8,  12,  16],
        [100,   4,   8,  12,  16]]])

In [46]:
np.array([(1, 2), (1, 3), (1, 4)])

array([[1, 2],
       [1, 3],
       [1, 4]])

In [85]:
augh = np.array([1, 2, 3])

x = np.delete(augh, 0)

In [88]:
a.shape[-2]

2