In [12]:
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import importlib
import wrf

from classes import (
    CoordinateField,
    ScalarField
)
from helpers import great_circle_distance

f = xr.open_dataset('../data/2013.11.18_regrid.nc')

In [4]:
c = CoordinateField(f.lat, f.lon, great_circle_distance)
s = ScalarField(f.U, c.dx, c.dy)

dUdx = s.get_ddx()
dUdy = s.get_ddy()

NameError: name 'CoordinateField' is not defined

In [14]:
f.Q

<xarray.DataArray 'Q' (XTIME: 67, lev: 10, lat: 270, lon: 370)>
[66933000 values with dtype=float32]
Coordinates:
  * lon      (lon) float64 3.0 3.15 3.3 3.45 3.6 ... 57.75 57.9 58.05 58.2 58.35
  * lat      (lat) float64 66.0 66.05 66.1 66.15 66.2 ... 79.3 79.35 79.4 79.45
  * XTIME    (XTIME) datetime64[ns] 2013-11-18T06:00:00 ... 2013-11-21
  * lev      (lev) float64 880.0 865.0 850.0 835.0 ... 525.0 500.0 475.0 450.0
Attributes:
    long_name:    Water vapor mixing ratio
    units:        kg kg-1
    description:  Water vapor mixing ratio
    FieldType:    104

In [52]:
a = np.array([
    [
        [
            [1,1,1,1],
            [2,2,2,2]
        ],
        [
            [3,3,3,3],
            [4,4,4,4]
        ],
    ],
    [
        [
            [5,5,5,5],
            [6,6,6,6]
        ],
        [
            [7,7,7,7],
            [8,8,8,8]
        ],
    ],
])
b = np.array(
    [
        [
            [1,1,1,1],
            [2,2,2,2]
        ],
        [
            [3,3,3,3],
            [4,4,4,4]
        ],
    ],
)

divisor = np.array([1, 2])

divisor[:, np.newaxis, np.newaxis]

divisor[:, np.newaxis, np.newaxis]/a

array([[[[1.        , 1.        , 1.        , 1.        ],
         [0.5       , 0.5       , 0.5       , 0.5       ]],

        [[0.66666667, 0.66666667, 0.66666667, 0.66666667],
         [0.5       , 0.5       , 0.5       , 0.5       ]]],


       [[[0.2       , 0.2       , 0.2       , 0.2       ],
         [0.16666667, 0.16666667, 0.16666667, 0.16666667]],

        [[0.28571429, 0.28571429, 0.28571429, 0.28571429],
         [0.25      , 0.25      , 0.25      , 0.25      ]]]])

In [45]:
[
    [
        [1]
    ],
    [
        [2]
    ],
]

4

In [63]:
a = np.array([[[1, 5, 9, 13], [2, 6, 10, 14]], [[4, 8, 12, 16], [4, 8, 12, 16]]])

In [64]:
np.gradient(a, axis=0)

array([[[3., 3., 3., 3.],
        [2., 2., 2., 2.]],

       [[3., 3., 3., 3.],
        [2., 2., 2., 2.]]])

In [78]:
def test_func(row):
    return np.sum(row)
    
np.apply_along_axis(test_func, 0, a)

array([[ 5, 13, 21, 29],
       [ 6, 14, 22, 30]])

In [81]:
np.insert(a, 0, [1, 100], axis=-1)

array([[[  1,   1,   5,   9,  13],
        [100,   2,   6,  10,  14]],

       [[  1,   4,   8,  12,  16],
        [100,   4,   8,  12,  16]]])

In [46]:
np.array([(1, 2), (1, 3), (1, 4)])

array([[1, 2],
       [1, 3],
       [1, 4]])

In [85]:
augh = np.array([1, 2, 3])

x = np.delete(augh, 0)

In [88]:
a.shape[-2]

2